# Containerfile that has dependencies for TSO500 post processing scripts

FROM debian:bookworm-20251117-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN uv sync

