# Containerfile that has dependencies for TSO500 post processing scripts

FROM debian:bookworm-20251117-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY ./containers/tso500_post_processing/pyproject.toml ./containers/tso500_post_processing/uv.lock ./

RUN apt update && apt install -y procps

RUN uv sync

